name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-base:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: 8.1
    - uses: actions/checkout@v3
    
    - name: Copy .env
      run: cp .env.example .env
      
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

  laravel-tests:

    needs: laravel-base

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nathanheffley/laravel-phpunit-action@master

  deploy-application:
    
    needs: laravel-tests

    runs-on: ubuntu-latest

    steps:
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: test
        environment_name: Test-env
        version_label: ${{ github.sha }}
        region: ap-southeast-1
        existing_bucket_name: mytestbucket090320230139
        deployment_package: deploy.zip
